# Generated by Django 3.2.4 on 2021-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_ratinganswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="project",
            name="fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
