# Generated by Django 3.2.4 on 2021-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_auto_20210622_1307"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="public")),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
