# Generated by Django 3.2.4 on 2021-07-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratinganswer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.ratingquestion",
            ),
            preserve_default=False,
        ),
    ]
