# Generated by Django 3.2.4 on 2021-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_ratinganswer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingquestion",
            name="changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
