# Generated by Django 3.2.4 on 2021-07-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0010_ratingquestion_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="name",
            field=models.CharField(
                blank=True, default="Open Review System", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="url",
            field=models.TextField(
                default="http://localhost:8000/", help_text="URL with ending slash"
            ),
        ),
        migrations.CreateModel(
            name="LoginKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("key", models.CharField(max_length=32)),
                ("used", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
