# Generated by Django 3.2.4 on 2021-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_auto_20210708_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="url",
            field=models.TextField(
                default="http://localhost:8000", help_text="URL without ending slash"
            ),
        ),
    ]
