# Generated by Django 3.2.5 on 2021-07-26 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0015_alter_entry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="reviewers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
