# Generated by Django 3.2.5 on 2021-08-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_entry_reviewers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['title', 'key'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
