# Generated by Django 3.2.16 on 2023-03-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_alter_entry_reviewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gforms_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="gforms_key",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="gforms_secret",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="gforms_title_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="gforms_url",
            field=models.CharField(default="", max_length=120),
        ),
    ]
