# Generated by Django 3.2.16 on 2023-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0019_auto_20230318_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assign_reviewers",
            field=models.BooleanField(
                default=False,
                help_text="Assigns all users that have access to project to be reviewers for newly imported entries",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="automatic_import",
            field=models.BooleanField(
                default=False,
                help_text="Tries to automatically import new entries from Gravity Forms every N minutes",
            ),
        ),
    ]
