# Generated by Django 3.2.16 on 2023-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0020_auto_20230318_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gforms_title_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
