# Generated by Django 3.2.16 on 2023-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_alter_project_gforms_title_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingquestion",
            name="scale",
            field=models.CharField(
                choices=[
                    ("1-10", "1 to 10"),
                    ("1-4", "1 to 4"),
                    ("text", "Text field"),
                    ("bool", "Yes or no"),
                ],
                max_length=64,
            ),
        ),
    ]
