# Generated by Django 3.2.16 on 2023-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0022_alter_ratingquestion_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingquestion",
            name="num_of_options",
            field=models.IntegerField(
                blank=True, help_text="If 1 to N scale, define N >= 2 here", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratingquestion",
            name="scale",
            field=models.CharField(
                choices=[
                    ("1-10", "1 to 10"),
                    ("1-N", "1 to N"),
                    ("text", "Text field"),
                    ("bool", "Yes or no"),
                ],
                max_length=64,
            ),
        ),
    ]
