# Generated by Django 3.2.23 on 2024-01-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20230318_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingquestion',
            name='include_in_statistics',
            field=models.BooleanField(default=False, help_text='1-10 is always calculated, check for 1 to N scale'),
        ),
    ]
