# Generated by Django 3.2.23 on 2024-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_ratingquestion_include_in_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingquestion',
            name='include_in_statistics',
            field=models.BooleanField(default=False, help_text='Include 1 to N scale question in statistics'),
        ),
    ]
