# Generated by Django 3.2.25 on 2025-03-01 16:21

from django.db import migrations, models


def index_search_text(apps, schema_editor):
    Entry = apps.get_model("web", "Entry")
    for entry in Entry.objects.all():
        entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0026_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="search_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;", "DROP EXTENSION IF EXISTS pg_trgm;"),
        migrations.RunSQL(
            "CREATE INDEX entry_search_text ON web_entry USING GIN (search_text gin_trgm_ops);"  # noqa
        ),
    ]
